name: Lint Docs Site

on:
  push:
    branches:
      - "fr/**"

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: yarn
      - name: Install
        run: cd docs && yarn
      - name: lint
        run: yarn lint

